// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0HRzjvwK690JvIDHULmEsZ0rzemdwIbM',
    appId: '1:627611705374:web:c138a93ed2c971bbd5ce0f',
    messagingSenderId: '627611705374',
    projectId: 'tirana-f1d9c',
    authDomain: 'tirana-f1d9c.firebaseapp.com',
    storageBucket: 'tirana-f1d9c.appspot.com',
    measurementId: 'G-388K36N1ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq0CHf6G-k8Xs6bHgkY4qvMgdCQ7BmXxU',
    appId: '1:627611705374:android:73b828b4f71e08e8d5ce0f',
    messagingSenderId: '627611705374',
    projectId: 'tirana-f1d9c',
    storageBucket: 'tirana-f1d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu_FEbyAP5JPnSYcgHtuc5gD22CFi7roc',
    appId: '1:627611705374:ios:22512b985e8b2f55d5ce0f',
    messagingSenderId: '627611705374',
    projectId: 'tirana-f1d9c',
    storageBucket: 'tirana-f1d9c.appspot.com',
    iosBundleId: 'com.example.jr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu_FEbyAP5JPnSYcgHtuc5gD22CFi7roc',
    appId: '1:627611705374:ios:7fd3bdf94287ecb5d5ce0f',
    messagingSenderId: '627611705374',
    projectId: 'tirana-f1d9c',
    storageBucket: 'tirana-f1d9c.appspot.com',
    iosBundleId: 'com.example.jr.RunnerTests',
  );
}
